// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type UpdateUser struct {
	ID           *string   `json:"id,omitempty"`
	DisplayName  *string   `json:"displayName,omitempty"`
	Email        *string   `json:"email,omitempty"`
	Products     []*string `json:"products,omitempty"`
	Roles        []*string `json:"roles,omitempty"`
	Integrations []*string `json:"integrations,omitempty"`
}

type User struct {
	ID           string    `json:"id"`
	DisplayName  string    `json:"displayName"`
	Email        string    `json:"email"`
	Products     []*string `json:"products"`
	Roles        []*string `json:"roles"`
	Integrations []*string `json:"integrations"`
}
